//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleOperationMappingInfo
    {
        public int RoleOperationMapId { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUserId { get; set; }
    
        public virtual OperationInfo OperationInfo { get; set; }
        public virtual UserRoleInfo UserRoleInfo { get; set; }
    }
}
