//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleInfo
    {
        public UserRoleInfo()
        {
            this.RoleOperationMappingInfoes = new HashSet<RoleOperationMappingInfo>();
            this.UserRoleMappingInfoes = new HashSet<UserRoleMappingInfo>();
        }
    
        public int UserRoleId { get; set; }
        public string UserRoleName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateUserId { get; set; }
    
        public virtual ICollection<RoleOperationMappingInfo> RoleOperationMappingInfoes { get; set; }
        public virtual ICollection<UserRoleMappingInfo> UserRoleMappingInfoes { get; set; }
    }
}
