//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.EmpServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpServiceReference.IHrmService")]
    public interface IHrmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetEmployees", ReplyAction="http://tempuri.org/IHrmService/GetEmployeesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/GetEmployeesServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hrm.Common.Dto.EmployeeDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hrm.Common.Dto.DepartmentDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hrm.Common.Dto.EmpolyeeHistoryDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hrm.Common.Dto.DesignationDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Hrm.Common.Dto.LocationDto))]
        Hrm.Common.Dto.EmployeeDto[] GetEmployees(Hrm.Common.Dto.BaseDto baseDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetEmployees", ReplyAction="http://tempuri.org/IHrmService/GetEmployeesResponse")]
        System.Threading.Tasks.Task<Hrm.Common.Dto.EmployeeDto[]> GetEmployeesAsync(Hrm.Common.Dto.BaseDto baseDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetDepartments", ReplyAction="http://tempuri.org/IHrmService/GetDepartmentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/GetDepartmentsServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        Hrm.Common.Dto.DepartmentDto[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetDepartments", ReplyAction="http://tempuri.org/IHrmService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<Hrm.Common.Dto.DepartmentDto[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetDesignations", ReplyAction="http://tempuri.org/IHrmService/GetDesignationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/GetDesignationsServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        Hrm.Common.Dto.DesignationDto[] GetDesignations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/GetDesignations", ReplyAction="http://tempuri.org/IHrmService/GetDesignationsResponse")]
        System.Threading.Tasks.Task<Hrm.Common.Dto.DesignationDto[]> GetDesignationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/CreateEmployee", ReplyAction="http://tempuri.org/IHrmService/CreateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/CreateEmployeeServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        void CreateEmployee(Hrm.Common.Dto.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/CreateEmployee", ReplyAction="http://tempuri.org/IHrmService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task CreateEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/EditEmployee", ReplyAction="http://tempuri.org/IHrmService/EditEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/EditEmployeeServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        void EditEmployee(Hrm.Common.Dto.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/EditEmployee", ReplyAction="http://tempuri.org/IHrmService/EditEmployeeResponse")]
        System.Threading.Tasks.Task EditEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/DeleteEmployee", ReplyAction="http://tempuri.org/IHrmService/DeleteEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IHrmService/DeleteEmployeeServiceFaultExceptionDtoFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        void DeleteEmployee(Hrm.Common.Dto.EmployeeDto employeeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHrmService/DeleteEmployee", ReplyAction="http://tempuri.org/IHrmService/DeleteEmployeeResponse")]
        System.Threading.Tasks.Task DeleteEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHrmServiceChannel : Hrm.Main.WebApplication.EmpServiceReference.IHrmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HrmServiceClient : System.ServiceModel.ClientBase<Hrm.Main.WebApplication.EmpServiceReference.IHrmService>, Hrm.Main.WebApplication.EmpServiceReference.IHrmService {
        
        public HrmServiceClient() {
        }
        
        public HrmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HrmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HrmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HrmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hrm.Common.Dto.EmployeeDto[] GetEmployees(Hrm.Common.Dto.BaseDto baseDto) {
            return base.Channel.GetEmployees(baseDto);
        }
        
        public System.Threading.Tasks.Task<Hrm.Common.Dto.EmployeeDto[]> GetEmployeesAsync(Hrm.Common.Dto.BaseDto baseDto) {
            return base.Channel.GetEmployeesAsync(baseDto);
        }
        
        public Hrm.Common.Dto.DepartmentDto[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<Hrm.Common.Dto.DepartmentDto[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public Hrm.Common.Dto.DesignationDto[] GetDesignations() {
            return base.Channel.GetDesignations();
        }
        
        public System.Threading.Tasks.Task<Hrm.Common.Dto.DesignationDto[]> GetDesignationsAsync() {
            return base.Channel.GetDesignationsAsync();
        }
        
        public void CreateEmployee(Hrm.Common.Dto.EmployeeDto employeeDto) {
            base.Channel.CreateEmployee(employeeDto);
        }
        
        public System.Threading.Tasks.Task CreateEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto) {
            return base.Channel.CreateEmployeeAsync(employeeDto);
        }
        
        public void EditEmployee(Hrm.Common.Dto.EmployeeDto employeeDto) {
            base.Channel.EditEmployee(employeeDto);
        }
        
        public System.Threading.Tasks.Task EditEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto) {
            return base.Channel.EditEmployeeAsync(employeeDto);
        }
        
        public void DeleteEmployee(Hrm.Common.Dto.EmployeeDto employeeDto) {
            base.Channel.DeleteEmployee(employeeDto);
        }
        
        public System.Threading.Tasks.Task DeleteEmployeeAsync(Hrm.Common.Dto.EmployeeDto employeeDto) {
            return base.Channel.DeleteEmployeeAsync(employeeDto);
        }
    }
}
