//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesInfo
    {
        public EmployeesInfo()
        {
            this.DepartmentInfoes = new HashSet<DepartmentInfo>();
            this.EmployeesInfo1 = new HashSet<EmployeesInfo>();
        }
    
        public int EmpId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> JobDesignationId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public Nullable<System.DateTime> DateOfJoin { get; set; }
    
        public virtual ICollection<DepartmentInfo> DepartmentInfoes { get; set; }
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        public virtual DesignationsInfo DesignationsInfo { get; set; }
        public virtual EmpolyeeHistoryInfo EmpolyeeHistoryInfo { get; set; }
        public virtual ICollection<EmployeesInfo> EmployeesInfo1 { get; set; }
        public virtual EmployeesInfo EmployeesInfo2 { get; set; }
    }
}
