//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpolyeeHistoryInfo
    {
        public int EmpId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        public virtual DesignationsInfo DesignationsInfo { get; set; }
        public virtual EmployeesInfo EmployeesInfo { get; set; }
    }
}
