//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HrManagementDbEntities : DbContext
    {
        public HrManagementDbEntities()
            : base("name=HrManagementDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DepartmentInfo> DepartmentInfoes { get; set; }
        public virtual DbSet<DesignationsInfo> DesignationsInfoes { get; set; }
        public virtual DbSet<EmployeesInfo> EmployeesInfoes { get; set; }
        public virtual DbSet<EmpolyeeHistoryInfo> EmpolyeeHistoryInfoes { get; set; }
        public virtual DbSet<LocationsInfo> LocationsInfoes { get; set; }
    }
}
