//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.UserAdminServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAdminServiceReference.IUserAdministration")]
    public interface IUserAdministration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAdministration/GetUserByName", ReplyAction="http://tempuri.org/IUserAdministration/GetUserByNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IUserAdministration/GetUserByNameServiceFaultExceptionDtoFault" +
            "", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        Hrm.Common.Dto.UserDto GetUserByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAdministration/GetUserByName", ReplyAction="http://tempuri.org/IUserAdministration/GetUserByNameResponse")]
        System.Threading.Tasks.Task<Hrm.Common.Dto.UserDto> GetUserByNameAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserAdministrationChannel : Hrm.Main.WebApplication.UserAdminServiceReference.IUserAdministration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAdministrationClient : System.ServiceModel.ClientBase<Hrm.Main.WebApplication.UserAdminServiceReference.IUserAdministration>, Hrm.Main.WebApplication.UserAdminServiceReference.IUserAdministration {
        
        public UserAdministrationClient() {
        }
        
        public UserAdministrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAdministrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAdministrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAdministrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hrm.Common.Dto.UserDto GetUserByName(string userName) {
            return base.Channel.GetUserByName(userName);
        }
        
        public System.Threading.Tasks.Task<Hrm.Common.Dto.UserDto> GetUserByNameAsync(string userName) {
            return base.Channel.GetUserByNameAsync(userName);
        }
    }
}
