//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hrm.Main.WebApplication.ReportGenerationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportGenerationServiceReference.IReportGenerationService")]
    public interface IReportGenerationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGenerationService/GenerateReport", ReplyAction="http://tempuri.org/IReportGenerationService/GenerateReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Hrm.Common.Dto.ServiceFaultExceptionDto), Action="http://tempuri.org/IReportGenerationService/GenerateReportServiceFaultExceptionDt" +
            "oFault", Name="ServiceFaultExceptionDto", Namespace="http://schemas.datacontract.org/2004/07/Hrm.Common.Dto")]
        void GenerateReport(Hrm.Common.Dto.ReportDataDto reportDataDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportGenerationService/GenerateReport", ReplyAction="http://tempuri.org/IReportGenerationService/GenerateReportResponse")]
        System.Threading.Tasks.Task GenerateReportAsync(Hrm.Common.Dto.ReportDataDto reportDataDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportGenerationServiceChannel : Hrm.Main.WebApplication.ReportGenerationServiceReference.IReportGenerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportGenerationServiceClient : System.ServiceModel.ClientBase<Hrm.Main.WebApplication.ReportGenerationServiceReference.IReportGenerationService>, Hrm.Main.WebApplication.ReportGenerationServiceReference.IReportGenerationService {
        
        public ReportGenerationServiceClient() {
        }
        
        public ReportGenerationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportGenerationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportGenerationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportGenerationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateReport(Hrm.Common.Dto.ReportDataDto reportDataDto) {
            base.Channel.GenerateReport(reportDataDto);
        }
        
        public System.Threading.Tasks.Task GenerateReportAsync(Hrm.Common.Dto.ReportDataDto reportDataDto) {
            return base.Channel.GenerateReportAsync(reportDataDto);
        }
    }
}
